version: '3.8'

services:
  mongodb:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all --keyFile /data/mongodb-keyfile
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kai
      - MONGO_INITDB_ROOT_PASSWORD=kai2025
      - MONGO_INITDB_DATABASE=datalex
      - MONGODB_REPLICA_SET_NAME=rs0
    volumes:
      - mongodb_data:/data/db
      - ./secrets/mongodb-keyfile:/data/mongodb-keyfile:ro
    networks:
      - app_network
    healthcheck:
      test: mongosh --eval "try { rs.status() } catch (err) { rs.initiate() }"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge